In [18]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
import seaborn as sn
import matplotlib.pyplot as plt

df = pd.read_csv('V:/data.csv')
df.head()

           x1          x2  y
0 -119.366669  115.000000  1
1 -101.108045   97.777159  1
2 -130.278658  106.767654  1
3 -114.703415  101.195477  1
4 -119.366669  115.000000  1

In [19]:
df.shape

(2227, 3)

In [20]:
df = df.apply (pd.to_numeric, errors='coerce')
df = df.dropna()
df = df.reset_index(drop=True)

In [21]:
df

              x1            x2  y
0    -119.366669  1.150000e+02  1
1    -101.108045  9.777716e+01  1
2    -130.278658  1.067677e+02  1
3    -114.703415  1.011955e+02  1
4    -119.366669  1.150000e+02  1
...          ...           ... ..
2214   98.714112  8.964312e+01  0
2215   96.633331  9.100000e+01  0
2216   85.673940  1.038393e+02  0
2217   78.958862  7.860537e+01  0
2218  109.624009  1.000000e+08  0

[2219 rows x 3 columns]

In [22]:
X = df[['x1','x2']]
X

              x1            x2
0    -119.366669  1.150000e+02
1    -101.108045  9.777716e+01
2    -130.278658  1.067677e+02
3    -114.703415  1.011955e+02
4    -119.366669  1.150000e+02
...          ...           ...
2214   98.714112  8.964312e+01
2215   96.633331  9.100000e+01
2216   85.673940  1.038393e+02
2217   78.958862  7.860537e+01
2218  109.624009  1.000000e+08

[2219 rows x 2 columns]

In [23]:
y = df[['y']]
y

      y
0     1
1     1
2     1
3     1
4     1
...  ..
2214  0
2215  0
2216  0
2217  0
2218  0

[2219 rows x 1 columns]

In [24]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [26]:
clf = DecisionTreeClassifier()
clf = clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)

In [27]:
print("Accuracy: ",metrics.accuracy_score(y_test, y_pred))

Accuracy:  0.9369369369369369

In [28]:
from matplotlib import pyplot as plt
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier 
from sklearn import tree

In [29]:
clf = DecisionTreeClassifier(random_state=1234)
model = clf.fit(X, y)

In [30]:
text_representation = tree.export_text(clf)
print(text_representation)

|--- feature_0 <= -66.01
|   |--- feature_1 <= -26.91
|   |   |--- class: 0
|   |--- feature_1 >  -26.91
|   |   |--- class: 1
|--- feature_0 >  -66.01
|   |--- feature_1 <= 16.17
|   |   |--- feature_0 <= 16.56
|   |   |   |--- feature_1 <= -31.99
|   |   |   |   |--- feature_0 <= 0.55
|   |   |   |   |   |--- feature_0 <= -13.33
|   |   |   |   |   |   |--- feature_1 <= -40.13
|   |   |   |   |   |   |   |--- feature_0 <= -21.07
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- feature_0 >  -21.07
|   |   |   |   |   |   |   |   |--- feature_0 <= -20.99
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |--- feature_0 >  -20.99
|   |   |   |   |   |   |   |   |   |--- feature_0 <= -19.23
|   |   |   |   |   |   |   |   |   |   |--- feature_0 <= -19.36
|   |   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |   |--- feature_0 >  -19.36
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |--- feature_0 >  -19.23
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- feature_1 >  -40.13
|   |   |   |   |   |   |   |--- feature_1 <= -39.78
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_1 >  -39.78
|   |   |   |   |   |   |   |   |--- feature_0 <= -23.11
|   |   |   |   |   |   |   |   |   |--- feature_0 <= -24.11
|   |   |   |   |   |   |   |   |   |   |--- feature_0 <= -34.45
|   |   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |   |--- feature_0 >  -34.45
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |--- feature_0 >  -24.11
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |--- feature_0 >  -23.11
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- feature_0 >  -13.33
|   |   |   |   |   |   |--- feature_1 <= -39.49
|   |   |   |   |   |   |   |--- feature_1 <= -51.30
|   |   |   |   |   |   |   |   |--- feature_0 <= -3.33
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- feature_0 >  -3.33
|   |   |   |   |   |   |   |   |   |--- feature_0 <= -2.91
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |--- feature_0 >  -2.91
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- feature_1 >  -51.30
|   |   |   |   |   |   |   |   |--- feature_1 <= -45.15
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |--- feature_1 >  -45.15
|   |   |   |   |   |   |   |   |   |--- feature_1 <= -41.78
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |--- feature_1 >  -41.78
|   |   |   |   |   |   |   |   |   |   |--- feature_0 <= -5.89
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |   |--- feature_0 >  -5.89
|   |   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- feature_1 >  -39.49
|   |   |   |   |   |   |   |--- feature_0 <= -11.67
|   |   |   |   |   |   |   |   |--- feature_1 <= -34.59
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- feature_1 >  -34.59
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_0 >  -11.67
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |--- feature_0 >  0.55
|   |   |   |   |   |--- feature_0 <= 15.13
|   |   |   |   |   |   |--- feature_1 <= -32.79
|   |   |   |   |   |   |   |--- feature_0 <= 10.42
|   |   |   |   |   |   |   |   |--- feature_0 <= 9.92
|   |   |   |   |   |   |   |   |   |--- feature_1 <= -54.71
|   |   |   |   |   |   |   |   |   |   |--- feature_1 <= -73.24
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |   |--- feature_1 >  -73.24
|   |   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |--- feature_1 >  -54.71
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |--- feature_0 >  9.92
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- feature_0 >  10.42
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_1 >  -32.79
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- feature_0 >  15.13
|   |   |   |   |   |   |--- class: 0
|   |   |   |--- feature_1 >  -31.99
|   |   |   |   |--- feature_0 <= 2.07
|   |   |   |   |   |--- feature_1 <= -3.24
|   |   |   |   |   |   |--- feature_0 <= -5.31
|   |   |   |   |   |   |   |--- feature_0 <= -29.84
|   |   |   |   |   |   |   |   |--- feature_1 <= -22.11
|   |   |   |   |   |   |   |   |   |--- feature_1 <= -27.31
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |--- feature_1 >  -27.31
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- feature_1 >  -22.11
|   |   |   |   |   |   |   |   |   |--- feature_1 <= -13.70
|   |   |   |   |   |   |   |   |   |   |--- feature_1 <= -14.47
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |   |--- feature_1 >  -14.47
|   |   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |--- feature_1 >  -13.70
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_0 >  -29.84
|   |   |   |   |   |   |   |   |--- feature_1 <= -28.50
|   |   |   |   |   |   |   |   |   |--- feature_1 <= -31.13
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |--- feature_1 >  -31.13
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- feature_1 >  -28.50
|   |   |   |   |   |   |   |   |   |--- feature_1 <= -11.11
|   |   |   |   |   |   |   |   |   |   |--- feature_0 <= -8.78
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 7
|   |   |   |   |   |   |   |   |   |   |--- feature_0 >  -8.78
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |--- feature_1 >  -11.11
|   |   |   |   |   |   |   |   |   |   |--- feature_0 <= -20.87
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- feature_0 >  -20.87
|   |   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- feature_0 >  -5.31
|   |   |   |   |   |   |   |--- feature_0 <= -2.00
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_0 >  -2.00
|   |   |   |   |   |   |   |   |--- feature_0 <= -0.48
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- feature_0 >  -0.48
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- feature_1 >  -3.24
|   |   |   |   |   |   |--- feature_0 <= -6.87
|   |   |   |   |   |   |   |--- feature_0 <= -25.59
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_0 >  -25.59
|   |   |   |   |   |   |   |   |--- feature_0 <= -24.16
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- feature_0 >  -24.16
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_0 >  -6.87
|   |   |   |   |   |   |   |--- feature_1 <= 7.34
|   |   |   |   |   |   |   |   |--- feature_1 <= -2.32
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |--- feature_1 >  -2.32
|   |   |   |   |   |   |   |   |   |--- feature_1 <= -0.89
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |--- feature_1 >  -0.89
|   |   |   |   |   |   |   |   |   |   |--- feature_0 <= -4.77
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |   |--- feature_0 >  -4.77
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3
|   |   |   |   |   |   |   |--- feature_1 >  7.34
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |--- feature_0 >  2.07
|   |   |   |   |   |--- feature_1 <= -21.52
|   |   |   |   |   |   |--- feature_1 <= -25.52
|   |   |   |   |   |   |   |--- feature_0 <= 10.18
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- feature_0 >  10.18
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_1 >  -25.52
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- feature_1 >  -21.52
|   |   |   |   |   |   |--- feature_0 <= 13.28
|   |   |   |   |   |   |   |--- feature_1 <= -0.24
|   |   |   |   |   |   |   |   |--- feature_1 <= -13.57
|   |   |   |   |   |   |   |   |   |--- feature_0 <= 4.06
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |--- feature_0 >  4.06
|   |   |   |   |   |   |   |   |   |   |--- feature_0 <= 7.13
|   |   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |   |--- feature_0 >  7.13
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3
|   |   |   |   |   |   |   |   |--- feature_1 >  -13.57
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- feature_1 >  -0.24
|   |   |   |   |   |   |   |   |--- feature_1 <= 3.68
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |--- feature_1 >  3.68
|   |   |   |   |   |   |   |   |   |--- feature_0 <= 4.58
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |--- feature_0 >  4.58
|   |   |   |   |   |   |   |   |   |   |--- feature_1 <= 6.94
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- feature_1 >  6.94
|   |   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- feature_0 >  13.28
|   |   |   |   |   |   |   |--- class: 0
|   |   |--- feature_0 >  16.56
|   |   |   |--- feature_1 <= -16.40
|   |   |   |   |--- feature_1 <= -39.18
|   |   |   |   |   |--- class: 1
|   |   |   |   |--- feature_1 >  -39.18
|   |   |   |   |   |--- feature_1 <= -38.86
|   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- feature_1 >  -38.86
|   |   |   |   |   |   |--- feature_0 <= 20.99
|   |   |   |   |   |   |   |--- feature_1 <= -25.62
|   |   |   |   |   |   |   |   |--- feature_1 <= -33.37
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- feature_1 >  -33.37
|   |   |   |   |   |   |   |   |   |--- feature_0 <= 18.97
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |   |--- feature_0 >  18.97
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_1 >  -25.62
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_0 >  20.99
|   |   |   |   |   |   |   |--- feature_1 <= -32.34
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_1 >  -32.34
|   |   |   |   |   |   |   |   |--- feature_1 <= -30.32
|   |   |   |   |   |   |   |   |   |--- feature_0 <= 26.18
|   |   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |   |   |--- feature_0 >  26.18
|   |   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- feature_1 >  -30.32
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |--- feature_1 >  -16.40
|   |   |   |   |--- feature_1 <= -1.26
|   |   |   |   |   |--- feature_1 <= -10.83
|   |   |   |   |   |   |--- feature_0 <= 24.63
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- feature_0 >  24.63
|   |   |   |   |   |   |   |--- feature_0 <= 34.75
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_0 >  34.75
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- feature_1 >  -10.83
|   |   |   |   |   |   |--- feature_0 <= 31.11
|   |   |   |   |   |   |   |--- feature_0 <= 21.66
|   |   |   |   |   |   |   |   |--- feature_1 <= -4.64
|   |   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |   |--- feature_1 >  -4.64
|   |   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_0 >  21.66
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_0 >  31.11
|   |   |   |   |   |   |   |--- feature_1 <= -6.68
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_1 >  -6.68
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |--- feature_1 >  -1.26
|   |   |   |   |   |--- feature_1 <= 0.81
|   |   |   |   |   |   |--- feature_1 <= 0.01
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- feature_1 >  0.01
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |--- feature_1 >  0.81
|   |   |   |   |   |   |--- class: 0
|   |--- feature_1 >  16.17
|   |   |--- feature_0 <= 1.65
|   |   |   |--- feature_0 <= -6.92
|   |   |   |   |--- feature_0 <= -23.08
|   |   |   |   |   |--- class: 1
|   |   |   |   |--- feature_0 >  -23.08
|   |   |   |   |   |--- feature_0 <= -22.64
|   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- feature_0 >  -22.64
|   |   |   |   |   |   |--- class: 1
|   |   |   |--- feature_0 >  -6.92
|   |   |   |   |--- feature_0 <= -4.15
|   |   |   |   |   |--- class: 0
|   |   |   |   |--- feature_0 >  -4.15
|   |   |   |   |   |--- class: 1
|   |   |--- feature_0 >  1.65
|   |   |   |--- feature_0 <= 6.99
|   |   |   |   |--- feature_0 <= 6.29
|   |   |   |   |   |--- feature_1 <= 22.21
|   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- feature_1 >  22.21
|   |   |   |   |   |   |--- feature_1 <= 23.61
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_1 >  23.61
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |--- feature_0 >  6.29
|   |   |   |   |   |--- class: 1
|   |   |   |--- feature_0 >  6.99
|   |   |   |   |--- feature_0 <= 21.53
|   |   |   |   |   |--- feature_0 <= 20.37
|   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- feature_0 >  20.37
|   |   |   |   |   |   |--- feature_0 <= 20.74
|   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_0 >  20.74
|   |   |   |   |   |   |   |--- feature_0 <= 21.17
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |   |--- feature_0 >  21.17
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |--- feature_0 >  21.53
|   |   |   |   |   |--- class: 0

In [31]:
with open('Decision_tree.log','w')as fout:
    fout.write(text_representation)